version: '3.1'
services:
  db:
    image: mysql
    container_name: pokemondb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - pokemondb_data:/var/lib/mysql

volumes:
  pokemondb_data: